### PR TITLE
New trees + layout squish

### PR DESCRIPTION
**Pull request by Arth101**
Added the new tree illustration as the treesizes.
Refactored the oldstyle layout to be a little smarter and better on mobile devices.
screenshot from 2016-12-12 15-01-56
screenshot from 2016-12-12 14-46-12
screenshot from 2016-12-12 14-46-21

### CODE REVIEW

**Comment by hypesystem** [comment]
Good stuff! 

Synes fejl siderne ser mærkelige ud med centreret tekst på mobil ...

Hvordan ser feks Administrer administratorer siden ud?

**Comment by Arth101** [comment]
@hypesystem ja, det med centreret tekst var faktisk en fejl. Er fikset nu.
screenshot from 2016-12-12 16-14-48
screenshot from 2016-12-12 16-14-55
screenshot from 2016-12-12 16-15-00
screenshot from 2016-12-12 16-15-20
screenshot from 2016-12-12 16-15-55

**Comment by hypesystem** [comment]
BUTTERFUL!

**Comment by hypesystem** [comment]
Missing version bump -- otherwise good to merge :smile:

**Comment by Arth101** [comment]
vbump is hot

**Comment by hypesystem** [comment]
Oskar Mike!

**Pull request merged**
